MMCPARTITION=$(fw_printenv -n mmcpartition)
if [ ${MMCPARTITION} -eq 4 ]; then
        TARGET=${SDCARD}rootfs2
else
        TARGET=${SDCARD}rootfs1
fi
SWUPDATE_MMCPARTITION="-e stable,${TARGET}"
SWUPDATE_ARGS="${SWUPDATE_ARGS} ${SWUPDATE_MMCPARTITION}"
