# GARDENA
MACHINE = "gardena-jetson-nano"
DISTRO = "gardena"

CONNECTIVITY_CHECK_URIS = "https://github.com/"

RDEPENDS:opkg-utils:remove = " bash"
INSANE_SKIP:opkg-utils += "file-rdeps"
RDEPENDS:mtd-utils-tests:remove = " bash"
INSANE_SKIP:mtd-utils-tests += "file-rdeps"
RDEPENDS:python3-tests:remove = " bash"
INSANE_SKIP:python3-tests += "file-rdeps"
RDEPENDS:tegra-tools-jetson-clocks:remove = " bash"
INSANE_SKIP:tegra-tools-jetson-clocks += "file-rdeps"
RDEPENDS:tegra-configs-nvstartup:remove = " bash"
RDEPENDS_tegra-configs-bootloader:remove = " bash"
RDEPENDS:tegra-nvs-base:remove = " bash"
RDEPENDS:tegra-nvphs-base:remove = " bash"
RDEPENDS:bash-completion:remove = " bash"
INSANE_SKIP:bash-completion += "file-rdeps"
RDEPENDS:libtool:remove = " bash"
INSANE_SKIP:libtool += "file-rdeps"
RDEPENDS:e2fsprogs-e2scrub:remove = " bash"
RDEPENDS:e2fsprogs-e2scrub:append = " zsh"
INSANE_SKIP:e2fsprogs-e2scrub += "file-rdeps"
RDEPENDS:pps-tools:remove = " bash"
RDEPENDS:pps-tools:append = " zsh"
INSANE_SKIP:pps-tools += "file-rdeps"
RDEPENDS:gflags-bash-completion:remove = " bash"
INSANE_SKIP:gflags-bash-completion += "file-rdeps"
RDEPENDS:opencv-apps:remove = " bash"
INSANE_SKIP:opencv-apps += "file-rdeps"

PACKAGECONFIG:pn-perl = ""
PACKAGECONFIG:pn-python3:class-target = ""
PACKAGECONFIG:remove = " readline"

# This will "save" the zip file and not package it into a .sh installer
CLANGSDK = "1"
#SDK_PACKAGING_FUNC = ""
SDK_ARCHIVE_TYPE = "tar.xz"
#SDKUSE_NLS = "no"

WHITEOUT_FILES = ""
