require conf/machine/jetson-nano-devkit-emmc.conf

IMAGE_CLASSES += "image_types_tegra_custom"
IMAGE_FSTYPES = "tegraflash"

CUDA_VERSION = "10.2"
#For the kernel compilation
HOSTTOOLS += "xxd bc"

ROOTFSPART_SIZE = "2147483648"

NVIDIA_DEVNET_MIRROR = "file:///${HOME}/nvidia/nvidia_sdk"

MACHINE_FEATURES_BACKFILL_CONSIDERED:append = " qemu-usermode"

RM_WORK_EXCLUDE:append = " linux-tegra u-boot-tegra"

KERNEL_DEVICETREE = "tegra210-p3448-0002-p3449-0000-b00.dtb"


